sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from sms_app.views import CustomSignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True), name='login'),   
    path('logout/', RedirectView.as_view(url='/accounts/logout/', permanent=True), name='logout'),
    path('signup/', RedirectView.as_view(url='/accounts/signup/', permanent=True), name='signup'),
]

sms_app/urls.py
from django.urls import path, re_path
from . import views

app_name = "sms_app"

urlpatterns = [
    path('home-page/', views.HomePageView.as_view(), name='homepage'),
    path('send-sms/', views.SendMessageView.as_view(), name='send_sms'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    re_path('^click/(?P<path>[\w=-]+)$', views.MyClickTrackingView.as_view(), name='click_tracking'),
    path('settings/edit-links/', views.EditLinksView.as_view(), name='edit_links'),
    path('edit-sms/<int:handle>/', views.EditMessageView.as_view(), name='edit_sms'),
    path('get-rating/', views.GetRatingView.as_view(), name='get-rating'),
]

templates/edit_links.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-container">
<!-- Page content-->
<div class="content-wrapper">
    <div class="content-heading">
        <div>Edit Links
            <small data-localize="dashboard.WELCOME"></small>
        </div>
        <!-- START Language list-->
        <div class="ml-auto">
            <div class="btn-group">
                <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">English</button>
                <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                    <a class="dropdown-item" href="#" data-set-lang="en">English</a>
                    <a class="dropdown-item" href="#" data-set-lang="es">Spanish</a>
                </div>
            </div>
        </div>
        <!-- END Language list-->
    </div>

    <div class="row">
        <div class="col-md-8 ">
            <h3 style="display: inline-block">Edit Links</h3>
            <a href="{% url 'sms_app:settings' %}">Back</a>
            <form action="{% url 'sms_app:edit_links' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="mobile">Google</label>
                    <input type="text" class="form-control" name="google" id="google" value="{{google}}">
                </div>
                <div class="form-group">
                    <label for="message">Facebook</label>
                    <input type="text" class="form-control" name="facebook" id="facebook" value="{{facebook}}">
                </div>
                <div class="form-group">
                    <label for="message">Yelp</label>
                    <input type="text" class="form-control" name="yelp" id="yelp" value="{{yelp}}">
                </div>
                <button class="btn btn-primary" type="submit">Save Links</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/send_sms.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="section-container">
    <!-- Page content-->
    <div class="content-wrapper">
        <div class="content-heading">
            <div>Send SMS
                <small data-localize="dashboard.WELCOME"></small>
            </div>
            <!-- START Language list-->
            <div class="ml-auto">
                <div class="btn-group">
                    <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">English</button>
                    <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                        <a class="dropdown-item" href="#" data-set-lang="en">English</a>
                        <a class="dropdown-item" href="#" data-set-lang="es">Spanish</a>
                    </div>
                </div>
            </div>
            <!-- END Language list-->
        </div>
        <div class="row">
            <div class="col-md-8">
            <h3>Send SMS</h3>
                <form action="" method="post">
                {% csrf_token %}
                    <input type="hidden" name="message_number" value="1">
                    <div class="form-group mobile_number">
                        <label for="mobile">Mobile Number</label>
                        <input type="text" class="form-control" name="mobile" id="mobile" placeholder="Mobile Number"
                        required>
                    </div>
                    <button class="btn btn-primary" type="submit">Send Message</button>
                    <h4>Message 1</h4>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <a href="{% url 'sms_app:edit_sms' 1 %}">Edit</a>
                        <a href=""></a>
                        <textarea name="first_message" id="first_message" class="form-control" cols="30" rows="10" 
                        readonly>{{first_msg}}</textarea>
                    </div>
                    <h4>Message 2</h4>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <a href="{% url 'sms_app:edit_sms' 2 %}">Edit</a>
                        <a href=""></a>
                        <textarea name="second_message" id="second_message" class="form-control" cols="30" rows="10" 
                        readonly>{{second_msg}}</textarea>
                    </div>
                    <h4>Message 3</h4>
                    <div class="form-group">
                        <label for="message">Message</label>
                        <a href="{% url 'sms_app:edit_sms' 3 %}">Edit</a>
                        <a href=""></a>
                        <textarea name="third_message" id="third_message" class="form-control" cols="30" rows="10" 
                        readonly>{{third_msg}}</textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}